/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package net.sf.jsignpdf;

import java.util.Iterator;
import java.util.List;
import java.util.Map;
import net.sf.jsignpdf.kie.KieOptions;
import net.sf.jsignpdf.kie.KieService;
import org.kie.server.api.model.instance.ProcessInstance;
import org.kie.server.api.model.instance.TaskSummary;
import org.kie.server.api.model.instance.TaskSummaryList;


/**
 *
 * @author maro
 */
public class SignPanel extends javax.swing.JPanel {

    private static final String jbpm_containerId = "Firma_2.2.6-SNAPSHOT";
    private static final Long jbpm_processInstanceId = 268L;
    /**
     * Creates new form panel2
     */
    public SignPanel(KieOptions kieOptions) {
        initComponents();
        
        // Obtento la lista de tareas
        // TODO: Cambiar por la lista de tareas
        System.out.println("OBTENER LISTA DE TAREAS");
        ProcessInstance pi = KieService.getProcessInstance(kieOptions.getJwt(), jbpm_containerId,kieOptions.getProcessInstanceId());
        if ( pi != null ) {
            txtNombre.setText(pi.getProcessName());
            txtVersion.setText(pi.getProcessVersion());
            txtDescrip.setText(pi.getProcessInstanceDescription());
            
            //TODO: ver datos de tarea y variables
//            TaskSummary[] ts = pi.getActiveUserTasks().getTasks();
//            for(TaskSummary t: ts) {
//                System.out.println(t.getDescription());
//            }
//            Map<String, Object> map = pi.getVariables();
//            
//            
//            Iterator<Map.Entry<String, Object>> iterator = map.entrySet().iterator();
//            while (iterator.hasNext()) {
//                Map.Entry<String, Object> entry = iterator.next();
//                System.out.println(entry.getKey() + ":" + entry.getValue());
//            }
        } else {
            lblDoc.setText("No se encontraron documentos para firmar.");
            jpanelFirma.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanelFirma = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtVersion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDescrip = new javax.swing.JTextField();
        lblDoc = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jLabel1.setText("Nombre");

        jLabel2.setText("Version");

        jLabel4.setText("Descrip");

        javax.swing.GroupLayout jpanelFirmaLayout = new javax.swing.GroupLayout(jpanelFirma);
        jpanelFirma.setLayout(jpanelFirmaLayout);
        jpanelFirmaLayout.setHorizontalGroup(
            jpanelFirmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelFirmaLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jpanelFirmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(61, 61, 61)
                .addGroup(jpanelFirmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNombre)
                    .addComponent(txtVersion)
                    .addComponent(txtDescrip, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(488, Short.MAX_VALUE))
        );
        jpanelFirmaLayout.setVerticalGroup(
            jpanelFirmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelFirmaLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jpanelFirmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpanelFirmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtVersion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpanelFirmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDescrip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(491, Short.MAX_VALUE))
        );

        add(jpanelFirma, java.awt.BorderLayout.CENTER);

        lblDoc.setBackground(new java.awt.Color(255, 255, 255));
        lblDoc.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lblDoc.setForeground(new java.awt.Color(0, 0, 0));
        lblDoc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDoc.setText("Documento pendiente de firma:");
        add(lblDoc, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jpanelFirma;
    private javax.swing.JLabel lblDoc;
    private javax.swing.JTextField txtDescrip;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtVersion;
    // End of variables declaration//GEN-END:variables
}
