/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package net.sf.jsignpdf;

import java.awt.BorderLayout;
import java.awt.GridLayout;
import java.awt.Toolkit;
import java.awt.datatransfer.DataFlavor;
import java.io.File;
import java.net.URL;
import java.util.List;
import java.util.Set;
import java.util.logging.Level;
import javax.net.ssl.SSLHandshakeException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.TransferHandler;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import static net.sf.jsignpdf.Constants.LOGGER;
import static net.sf.jsignpdf.Constants.RES;
import net.sf.jsignpdf.kie.KieOptions;
import net.sf.jsignpdf.types.CertificationLevel;
import net.sf.jsignpdf.types.HashAlgorithm;
import net.sf.jsignpdf.types.PDFEncryption;
import net.sf.jsignpdf.types.PrintRight;
import net.sf.jsignpdf.utils.ConfigProvider;
import net.sf.jsignpdf.utils.GuiUtils;
import net.sf.jsignpdf.utils.KeyStoreUtils;
import net.sf.jsignpdf.utils.PKCS11Utils;

/**
 *
 * @author maro
 */
public class SimpleSignPdfForm extends javax.swing.JFrame implements SignResultListener {
    
    private static final long serialVersionUID = 1L;
    private boolean autoclose = false;
    
    private TokenDetectPanel panel1;
    private SignPanel panel2;
    
    private Set<String> tmpKsTypes;
    
    private KieOptions kieOptions;

    /**
     * Creates new form SimpleSignPdfForm
     */
    public SimpleSignPdfForm() {
        initComponents();
    }
    
    public SimpleSignPdfForm(int aCloseOperation, KieOptions kieOptions) {
        initComponents();
        
        this.kieOptions = kieOptions;
        // PKCS11Utils.unregisterProviders();
        // PKCS11Utils.registerProviders(ConfigProvider.getInstance().getProperty("pkcs11config.path"));
        showTokenDetectPanel();
//        tmpKsTypes = KeyStoreUtils.getKeyStores();
//        for(String t: tmpKsTypes) {
//            System.out.println(t);
//        }
//        if (tmpKsTypes.contains("PKCS11")) {
//            showTokenDetectPanel();
//        } else {
//            showSignPanel(tmpKsTypes);
//        }
    }
    
    public void showTokenDetectPanel() {
        panel1 = new TokenDetectPanel(this);
//        panel1.setSize(300,300);
//        panel1.setLocation(0,0);
        panel1.setLayout(new GridLayout(0, 1));
        
        content.removeAll();
        content.add(panel1,BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
        panel1.registerPK11Providers();
    }
    
    public void showSignPanel(Set<String> tmpKsTypes) {
        panel2 = new SignPanel(this.kieOptions);
//        panel2.setSize(300,300);
//        panel2.setLocation(0,0);
        panel1.setLayout(new GridLayout(0, 1));
        content.removeAll();
        content.add(panel2,BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        infoDialog = new javax.swing.JFrame();
        infoScrollPane = new javax.swing.JScrollPane();
        infoTextArea = new javax.swing.JTextArea();
        btnInfoClose = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        content = new javax.swing.JPanel();
        btnPanel2 = new javax.swing.JButton();
        btnPanel1 = new javax.swing.JButton();

        infoTextArea.setColumns(20);
        infoTextArea.setRows(5);
        infoScrollPane.setViewportView(infoTextArea);

        infoDialog.getContentPane().add(infoScrollPane, java.awt.BorderLayout.CENTER);

        btnInfoClose.setText("jButton2");
        infoDialog.getContentPane().add(btnInfoClose, java.awt.BorderLayout.PAGE_END);

        infoDialog.getAccessibleContext().setAccessibleName("PDF Signer Output");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        content.setBackground(new java.awt.Color(255, 255, 255));
        content.setLayout(new java.awt.GridLayout(1, 0));

        btnPanel2.setText("jButton3");
        btnPanel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPanel2ActionPerformed(evt);
            }
        });

        btnPanel1.setText("jButton2");
        btnPanel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPanel1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnPanel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 430, Short.MAX_VALUE)
                        .addComponent(btnPanel2)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPanel2)
                    .addComponent(btnPanel1))
                .addGap(27, 27, 27))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 610, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPanel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPanel1ActionPerformed
        
    }//GEN-LAST:event_btnPanel1ActionPerformed

    private void btnPanel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPanel2ActionPerformed
        
    }//GEN-LAST:event_btnPanel2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SimpleSignPdfForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SimpleSignPdfForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SimpleSignPdfForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SimpleSignPdfForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SimpleSignPdfForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInfoClose;
    private javax.swing.JButton btnPanel1;
    private javax.swing.JButton btnPanel2;
    private javax.swing.JPanel content;
    private javax.swing.JFrame infoDialog;
    private javax.swing.JScrollPane infoScrollPane;
    private javax.swing.JTextArea infoTextArea;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

    @Override
    public void signerFinishedEvent(Throwable e) {
        if (e instanceof SSLHandshakeException) {
            JOptionPane.showMessageDialog(this, RES.get("error.sslHandshakeException"), "Error", JOptionPane.WARNING_MESSAGE);
        }
        btnInfoClose.setEnabled(true);
        infoDialog.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        if (!btnInfoClose.hasFocus())
            btnInfoClose.requestFocus();
        if (autoclose)
            btnInfoCloseActionPerformed(null);
    }
    
    private void btnInfoCloseActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnInfoCloseActionPerformed
        infoDialog.setVisible(false);
        setVisible(true);
    }// GEN-LAST:event_btnInfoCloseActionPerformed
}
