/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package net.sf.jsignpdf;

import java.util.Set;
import net.sf.jsignpdf.kie.KieOptions;
import net.sf.jsignpdf.utils.PKCS11Utils;
import net.sf.jsignpdf.utils.ConfigProvider;
import net.sf.jsignpdf.utils.KeyStoreUtils;

/**
 *
 * @author maro
 */
public class TokenDetectPanel extends javax.swing.JPanel {

    SimpleSignPdfForm parentForm;
    
    /**
     * Creates new form panel1
     */
    public TokenDetectPanel() {
        initComponents();
    }
    
    public TokenDetectPanel(SimpleSignPdfForm signForm) {
        initComponents();
        this.btnDetectToken.setVisible(false);
        parentForm = signForm;
    }
    
    public void registerPK11Providers() {
        lblMessage.setText("Detectando token...");
        PKCS11Utils.unregisterProviders();
        PKCS11Utils.registerProviders(ConfigProvider.getInstance().getProperty("pkcs11config.path"));        // TODO add your handling code here:
        final Set<String> tmpKsTypes = KeyStoreUtils.getKeyStores();
        for(String t: tmpKsTypes) {
            System.out.println(t);
        }
        if (tmpKsTypes.contains("PKCS11")) {
            System.out.println("ENcontrado - muestro panel de firma");
            parentForm.showSignPanel(tmpKsTypes);
        } else {
            lblMessage.setText("No se encontró un dispositivo de firma.");
            System.out.println("NO ENCONTRADO - REINTENTAR");
            this.btnDetectToken.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        lblMessage = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnDetectToken = new javax.swing.JButton();

        jPanel1.setLayout(new java.awt.GridBagLayout());

        lblMessage.setText("PANEL TOKEN");
        jPanel1.add(lblMessage, new java.awt.GridBagConstraints());

        jPanel2.setLayout(new java.awt.GridBagLayout());

        btnDetectToken.setLabel("Reintentar");
        btnDetectToken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetectTokenActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(37, 2, 38, 6);
        jPanel2.add(btnDetectToken, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDetectTokenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetectTokenActionPerformed
        registerPK11Providers();
    }//GEN-LAST:event_btnDetectTokenActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetectToken;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblMessage;
    // End of variables declaration//GEN-END:variables
}
